rpm install: Add integration test for env checking after RPM install
aws/aws-nitro-enclaves-cli pull request #396
Opened 2022-07-26 17:30 UTC by meerd

Note: Merging Gabriel's lingering PR.

Added a separate integration test which checks if various components
are configured correctly (vsock-proxy service, hugetlbfs and CPU pool)
after installing the Nitro CLI package.

Signed-off-by: Gabriel Bercaru <bercarug@amazon.com>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-27 11:42 UTC, andraprs approved these changes

2022-08-08 07:43 UTC, sabin-rapan requested changes

2022-08-08 07:43 UTC, sabin-rapan commented on tests/integration/test_setup.py
> +    Sample path which is to be checed:
s/checed/checked

2022-08-08 07:43 UTC, sabin-rapan commented on tests/integration/test_setup.py
> +    status = os.system('systemctl status vsock-proxy.service > /dev/null 2>&1')
Why check twice?

2024-04-05 15:09 UTC, closed without merging