calincoman: dockerless nitro-cli
aws/aws-nitro-enclaves-cli pull request #399
Opened 2022-08-04 07:59 UTC by calincoman

*Description of changes:*
- Added new functions for handling the cache logic
- Fixed issues raised by Erdem

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-05 10:10 UTC, petreeftime requested changes
Can you run `cargo clippy` over the code and fix the issues?

2022-08-05 10:10 UTC, petreeftime commented on enclave_build/src/utils.rs
> +        let cmd_obj = config_obj.get("Cmd").expect("'Cmd' field is missing.");
Should return errors instead of crashing here.

2022-08-05 10:10 UTC, petreeftime commented on enclave_build/src/image_cache.rs
> +        }
Replace with
```rust
expressions.map(|expr| writeln!(...).map_error(...)).collect()?;
```

2022-08-05 10:10 UTC, petreeftime commented on enclave_build/src/image_cache.rs
> +        let output_file = match File::create(output_path) {
use map_err

2022-08-05 10:10 UTC, petreeftime commented on enclave_build/src/cache_manager.rs
> +        let image_hash: Option<&String> = match self.values.get(uri) {
I don't understand what this match does?

2022-08-05 10:12 UTC, petreeftime commented on enclave_build/src/image_cache.rs
> +    pub fn get_image_folder_path(image_ref: &Reference, cache_manager: &CacheManager) -> Result<String, CacheError> {
Should return `Path` or `PathBuf` instead of String.

2022-08-05 10:14 UTC, petreeftime commented on enclave_build/src/image_cache.rs
> +    //     // => should have some default root folder for this case
`$XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used. `

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

2022-08-05 10:18 UTC, petreeftime commented on enclave_build/src/image_cache.rs
> +    //     // => should have some default root folder for this case
`$XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be seperated with a colon ':'.

If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. `

For writing, I would XDG_DATA_HOME or the default, if this is not set. When searching for a container image, the cli should also look into XDG_DATA_DIRS, but I would add this later on.

2022-08-05 10:27 UTC, petreeftime commented on enclave_build/src/cache_manager.rs
> +        let image_hash: Option<&String> = match self.values.get(uri) {
This whole function can be re-written as
```rust
self.values.get(uri).map(|s| s.to_string()).ok_or_else(|err| ...)
```

2022-08-08 07:26 UTC, sabin-rapan commented
Please write decent commit messages and titles.
Also fix the CI failures

2022-09-20 07:49 UTC, closed without merging